const GET_RECIPES = 'GET_RECIPES';
const LOAD_DATA = 'LOAD_DATA';
const FILTER_RECIPES_BY_DIETS = 'FILTER_RECIPES_BY_DIETS';
const FILTER_RECIPES_BY_ORDER= 'FILTER_RECIPES_BY_ORDER';

export const types ={
    GET_RECIPES,
    LOAD_DATA,
    FILTER_RECIPES_BY_DIETS,
    FILTER_RECIPES_BY_ORDER
}
