const GET_RECIPES = 'GET_RECIPES';
const LOAD_DATA = 'LOAD_DATA';
const FILTER_RECIPES_BY_DIETS = 'FILTER_RECIPES_BY_DIETS';
const FILTER_RECIPES_BY_ORDER= 'FILTER_RECIPES_BY_ORDER';
const FILTER_RECIPES_BY_SOURCE = 'FILTER_RECIPES_BY_SOURCE';
const FILTER_ASC_DESC = 'FILTER_ASC_DESC';
const SEARCH_TITLE = 'SEARCH_TITLE';
const GET_TYPES = 'GET_TYPES';
const POST_RECIPE = 'POST_RECIPE';

export const types ={
    GET_RECIPES,
    LOAD_DATA,
    FILTER_RECIPES_BY_DIETS,
    FILTER_RECIPES_BY_ORDER,
    FILTER_RECIPES_BY_SOURCE,
    FILTER_ASC_DESC,
    SEARCH_TITLE,
    GET_TYPES,
    POST_RECIPE
}

